//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_HeCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCopy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookCopy()
        {
            this.LoanDetails = new HashSet<LoanDetail>();
        }
    
        public int BookCopy_ID { get; set; }
        public Nullable<int> Book_ID { get; set; }
        public Nullable<int> Year_publish { get; set; }
        public Nullable<int> Publisher_ID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDetail> LoanDetails { get; set; }
    }
}
