//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_HeCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Fine_ID { get; set; }
        public int Detail_ID { get; set; }
        public int Reader_ID { get; set; }
        public decimal Library_fine { get; set; }
        public string Reason { get; set; }
    
        public virtual LoanDetail LoanDetail { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
