//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_HeCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanDetail()
        {
            this.Fines = new HashSet<Fine>();
        }
    
        public int Detail_ID { get; set; }
        public Nullable<int> Loan_ID { get; set; }
        public Nullable<int> BookCopy_ID { get; set; }
        public System.DateTime Returnday { get; set; }
        public decimal Deposit { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fine> Fines { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
